### ISSUE TITLE
AI decided to take a break

### ISSUE THREAD

**Issue by codekeyz** [mkobuolys/ai-photo-scavenger-hunt#1]
I've followed the guide to running this but i just end up at this screen.

```bash
flutter run --dart-define API_KEY="AIzaSysome-weird-key-6vZ7Uds"
```

![error](https://github.com/mkobuolys/ai-photo-scavenger-hunt/assets/22515508/597e6ae3-53b1-4add-9cc3-2c18dbd7dcae)

**Comment by mkobuolys** [comment]
Hi! I would suggest REMOVING this issue and recreating it since you just shared your API key 👀 Secondly, double-check if Gemini API is available in your region.

**Comment by codekeyz** [comment]
> Hi! I would suggest REMOVING this issue and recreating it since you just shared your API key 👀 Secondly, double-check if Gemini API is available in your region.

Oh no, that's not a real API Key
